import React, { useState } from 'react';
import { ProjectIdea } from '../../types';
import {
  X,
  Printer,
  Copy,
  Check,
  FileText,
  Download,
  ShieldCheck,
  Sparkles,
} from 'lucide-react';

interface SynopsisExportModalProps {
  project: ProjectIdea;
  onClose: () => void;
  onToast: (msg: string, type?: 'success' | 'info' | 'warning' | 'error') => void;
}

export const SynopsisExportModal: React.FC<SynopsisExportModalProps> = ({
  project,
  onClose,
  onToast,
}) => {
  const [copied, setCopied] = useState(false);

  // Generate clean academic markdown representation
  const generateMarkdown = () => {
    return `# FINAL-YEAR PROJECT SYNOPSIS
**Project Title:** ${project.title}
**Domain:** ${project.domain}
**Target Duration:** ${project.estimatedDuration} | **Team Size:** ${project.teamSize}
**Evaluation Scores:** Innovation: ${project.innovationScore}/100 | Practicality: ${project.practicalityScore}/100 | Placement Relevance: ${project.placementRelevance}/100

---

## 1. Abstract & Problem Statement
${project.problemStatement}

## 2. Proposed Solution & Innovation
${project.solutionOverview}

## 3. Project Objectives & Target Beneficiaries
Target Stakeholders:
${project.expectedUsers.map(u => `- ${u}`).join('\n')}

Key Feasibility Resources:
${project.requiredResources.map(r => `- ${r}`).join('\n')}

## 4. System Architecture
**Design Pattern:** ${project.architecture.pattern}
**Architectural Summary:** ${project.architecture.summary}

Primary Modules & Nodes:
${project.architecture.nodes.map(n => `- **${n.label}** (${n.category} tier): ${n.role} [Implemented via ${n.technology}]`).join('\n')}

## 5. Technology Stack Selection & Rationale
${project.recommendedTechnologies.map(t => `- **${t.name}** (${t.category}): ${t.reason}`).join('\n')}

## 6. Functional Capabilities & Feature Tiers
### Core MVP Features:
${project.coreFeatures.map(f => `- **${f.title}**: ${f.description} (Complexity: ${f.complexity}, Est: ${f.estimatedHours}h)`).join('\n')}

### Intermediate & Advanced Features:
${project.intermediateFeatures.map(f => `- **${f.title}**: ${f.description}`).join('\n')}
${project.advancedFeatures.map(f => `- **${f.title}**: ${f.description}`).join('\n')}

### Dedicated AI/ML Pipeline:
${project.aiFeatures.map(f => `- **${f.title}**: ${f.description}`).join('\n')}

## 7. Database Entities Specification
${project.databaseDesign.map(e => `### Table: ${e.name}
${e.description}
Columns: ${e.fields.map(f => `${f.name} (${f.type}${f.constraints ? ', ' + f.constraints : ''})`).join('; ')}
`).join('\n')}

## 8. Eight-Phase Development Roadmap
${project.roadmap.map(p => `### Phase ${p.phaseNumber}: ${p.phaseName} (${p.estimatedDuration})
Objective: ${p.objective}
Tasks:
${p.tasks.map(t => `- [ ] ${t.title} (~${t.estimatedDays} days)`).join('\n')}
`).join('\n')}

## 9. Technical Risks & Mitigations
${project.risks.map(r => `- **Risk:** ${r.risk}\n  - **Mitigation:** ${r.mitigation}`).join('\n')}

## 10. Future Academic Scope
${project.futureScope.map(s => `- ${s}`).join('\n')}

---
*Generated by ProjectForge AI Academic Platform*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    onToast('Project synopsis copied to clipboard as Markdown!', 'success');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(project, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${project.id}_blueprint.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    onToast('Project blueprint JSON downloaded!', 'success');
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4 sm:p-6">
      <div className="relative w-full max-w-4xl rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl p-6 sm:p-8 space-y-6 max-h-[90vh] overflow-y-auto">
        {/* Modal Controls Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800 no-print">
          <div className="flex items-center gap-2.5">
            <div className="p-2.5 rounded-xl bg-forge-500/20 text-forge-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-xl font-extrabold text-white">
                Academic Project Synopsis
              </h3>
              <p className="text-xs text-slate-400">
                Formatted for initial faculty approval and university submission.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-colors"
              title="Copy markdown synopsis"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-colors"
              title="Download raw JSON"
            >
              <Download className="w-3.5 h-3.5" />
              <span>JSON</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-4 py-1.5 rounded-xl text-xs font-bold bg-forge-600 hover:bg-forge-500 text-white shadow-glow flex items-center gap-1.5 transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Synopsis</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 ml-2"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Formal Printable Document Body */}
        <div className="p-8 rounded-2xl bg-white text-slate-900 shadow-inner font-sans space-y-6 print-card text-xs sm:text-sm">
          {/* Document Header */}
          <div className="text-center border-b pb-6 border-slate-300">
            <span className="text-[11px] font-bold uppercase tracking-widest text-slate-500 block">
              FINAL-YEAR CAPSTONE PROJECT SYNOPSIS
            </span>
            <h1 className="text-xl sm:text-2xl font-black text-slate-950 mt-1 leading-tight">
              {project.title}
            </h1>
            <p className="text-xs text-slate-600 italic mt-1 font-serif">
              &ldquo;{project.tagline}&rdquo;
            </p>

            <div className="flex flex-wrap items-center justify-center gap-4 text-xs font-semibold text-slate-700 mt-3 pt-3 border-t border-slate-200">
              <span>Domain: <strong>{project.domain}</strong></span>
              <span>•</span>
              <span>Level: <strong>{project.difficulty}</strong></span>
              <span>•</span>
              <span>Duration: <strong>{project.estimatedDuration}</strong></span>
              <span>•</span>
              <span>Team: <strong>{project.teamSize}</strong></span>
            </div>
          </div>

          {/* Section 1: Problem Statement */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              1. Abstract & Problem Statement
            </h2>
            <p className="text-slate-700 leading-relaxed text-justify">
              {project.problemStatement}
            </p>
          </div>

          {/* Section 2: Solution Overview */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              2. Proposed Solution & Technical Approach
            </h2>
            <p className="text-slate-700 leading-relaxed text-justify">
              {project.solutionOverview}
            </p>
          </div>

          {/* Section 3: Architecture Summary */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              3. System Architecture ({project.architecture.pattern})
            </h2>
            <p className="text-slate-700 leading-relaxed mb-3">
              {project.architecture.summary}
            </p>
            <div className="grid grid-cols-2 gap-2 text-[11px]">
              {project.architecture.nodes.map(n => (
                <div key={n.id} className="p-2 bg-slate-100 rounded border border-slate-200">
                  <span className="font-bold block text-slate-900">{n.label} ({n.category})</span>
                  <span className="text-slate-600">{n.role} • Tech: {n.technology}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Recommended Technologies */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              4. Technology Stack & Rationale
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px]">
              {project.recommendedTechnologies.map((t, idx) => (
                <div key={idx} className="p-2 bg-slate-50 rounded border border-slate-200">
                  <span className="font-bold text-slate-900">{t.name}</span>{' '}
                  <span className="text-slate-500 uppercase font-mono text-[9px]">({t.category})</span>
                  <p className="text-slate-600 mt-0.5">{t.reason}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Section 5: Roadmap Timeline */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              5. Standardized 8-Phase Development Roadmap
            </h2>
            <div className="grid grid-cols-2 gap-2 text-[11px]">
              {project.roadmap.map(phase => (
                <div key={phase.phaseNumber} className="p-2 border border-slate-200 rounded">
                  <span className="font-bold text-slate-900 block">
                    Phase {phase.phaseNumber}: {phase.phaseName}
                  </span>
                  <span className="text-slate-500 text-[10px] block">{phase.estimatedDuration}</span>
                  <span className="text-slate-600">{phase.objective}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 6: Risks & Mitigations */}
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-900 border-b pb-1 mb-2">
              6. Risk Assessment & Faculty Defense Safeguards
            </h2>
            <div className="space-y-1.5 text-[11px]">
              {project.risks.map((r, i) => (
                <div key={i}>
                  <strong className="text-slate-900">Risk #{i + 1}:</strong> {r.risk} &rarr;{' '}
                  <span className="text-slate-700 italic">Mitigation: {r.mitigation}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Document Footer */}
          <div className="pt-4 border-t text-[10px] text-slate-400 text-center flex justify-between">
            <span>ProjectForge AI — Academic Capstone Specification</span>
            <span>Date Generated: {new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>
    </div>
  );
};
